florianl/bluebox

EXAMPLE.md
main.go
main_test.go

deprecate -d and introduce -e and -r

---

init.go

move mount cmd to mkdir

---

README.md
bluebox.go
init.go
template.go

use templates

---

.github/workflows/example.yml

add CI/CD example for github action

---

README.md

remove future ideas from README

---

go.mod
go.sum
init.go

replace os/exec with golang.org/x/sys/execabs

---

DEBUGGING.md

add DEBUGGING guide

---

template.go

add safe guard to template

---

.github/workflows/example.yml
.github/workflows/staticcheck.yml
.github/workflows/tests.yml

github action: more fine grade triggers

---

init.go
main.go

move up creation of temporary directory

---

main.go

use helper to exit on failure

---

template.go

use correct variables for operands

---

main.go

check embedded executable

---

template.go

If one of the programs run by init produces a large amount of stderr or
stdout, the pipe buffer in kernelspace will eventually fill up, causing
the launched program to block in a write. Init likewise will be blocked
on Wait4, waiting for the launched program to finish, resulting in a
deadlock.
This commit spins up two goroutines to constanly drain data from stdout
and stderr so this doesn't happen.

Fix pipe-related deadlock

---

DEBUGGING.md
go.mod
go.sum
init.go
main.go
template.go

switch to execute on TMPFS

---

bluebox.go

Reorder output and print errors

---

template.go

Add a safeguard for `bluebox-init` to make it safe to run in a non `TMPFS_MAGIC` environment.

add safeguard for shutdown

---

DEBUGGING.md

rectify debugging instructions

---

main.go
main_gteq_118.go
main_lt_118.go

add -version flag

---

.github/workflows/staticcheck.yml
.github/workflows/tests.yml

actions: add Go 1.19

---

initramfs/init.go
initramfs/initramfs.go

remove debug statements

---

README.md

README: add API note
